import {forwardRef,useEffect,useId,useRef,useState,type ChangeEventHandler,type CSSProperties,type HTMLAttributes,type InputHTMLAttributes,type ReactNode} from 'react';
import {CircleX,Search,Minus,Plus,ChevronLeft,ChevronRight,ChevronDown} from 'lucide-react';
import {GlassSurface,type GlassSurfaceProps} from './surface.js';
import {assignRef,classes,useControllable,useTheme,type MaterialProps} from './context.js';
import {GlassPopover} from './popover.js';

export interface GlassTextFieldProps extends Omit<InputHTMLAttributes<HTMLInputElement>,'size'|'value'|'defaultValue'>,Pick<MaterialProps,'appearance'> {
  label?:string;value?:string;defaultValue?:string;onValueChange?:(value:string)=>void;clearable?:boolean;leading?:ReactNode;trailing?:ReactNode;error?:string;
}
export const GlassTextField=forwardRef<HTMLInputElement,GlassTextFieldProps>(function GlassTextField({label,value:controlled,defaultValue='',onValueChange,clearable=false,leading,trailing,error,appearance,className,style,onChange,id:givenId,...props},ref){
  const id=useId(),fieldId=givenId??id,inner=useRef<HTMLInputElement>(null),theme=useTheme({appearance});
  const [value,setValue]=useControllable(controlled,defaultValue,onValueChange);
  return <div className={classes('prism-field',className)} data-appearance={theme.appearance} data-disabled={props.disabled||undefined} data-invalid={Boolean(error)||props['aria-invalid']||undefined} style={style}>
    {label&&<label htmlFor={fieldId}>{label}</label>}<div className="prism-field-body">{leading&&<span className="prism-field-leading">{leading}</span>}<input {...props} id={fieldId} ref={node=>{inner.current=node;assignRef(ref,node);}} value={value} aria-invalid={error?'true':props['aria-invalid']} aria-describedby={[props['aria-describedby'],error?`${id}-error`:undefined].filter(Boolean).join(' ')||undefined} onChange={event=>{onChange?.(event);if(!event.defaultPrevented)setValue(event.currentTarget.value);}}/>
    {clearable&&value&&!props.readOnly&&<button type="button" disabled={props.disabled} aria-label={`Clear ${label??props['aria-label']??'text'}`} className="prism-field-clear" onClick={()=>{setValue('');inner.current?.focus();}}><CircleX size={17} aria-hidden="true"/></button>}{trailing&&<span className="prism-field-trailing">{trailing}</span>}</div>{error&&<span className="prism-field-error" id={`${id}-error`} role="alert">{error}</span>}
  </div>;
});
export interface GlassSearchFieldProps extends Omit<GlassTextFieldProps,'type'|'leading'|'trailing'|'error'>,Omit<MaterialProps,'appearance'> {onSearch?:(value:string)=>void;onCancel?:()=>void;cancelLabel?:string;cancelable?:boolean;floating?:boolean}
export const GlassSearchField=forwardRef<HTMLInputElement,GlassSearchFieldProps>(function GlassSearchField({value:controlled,defaultValue='',onValueChange,onSearch,onCancel,cancelLabel='Cancel',cancelable=true,floating=true,variant,appearance,tintLevel,tint,dimming,preset,backdrop,refractionTarget,optics,present,onPresenceChange,label,clearable=true,className,style,onChange,onKeyDown,onFocus,onBlur,...props},ref){
  const [value,setValue]=useControllable(controlled,defaultValue,onValueChange),[focused,setFocused]=useState(false),input=useRef<HTMLInputElement>(null);
  const body=<div className="prism-search-body"><Search size={20} aria-hidden="true"/><input {...props} ref={node=>{input.current=node;assignRef(ref,node);}} type="search" value={value} aria-label={props['aria-label']??label??'Search'} placeholder={props.placeholder??'Search'} onChange={event=>{onChange?.(event);if(!event.defaultPrevented)setValue(event.currentTarget.value);}} onKeyDown={event=>{onKeyDown?.(event);if(event.key==='Enter'&&!event.defaultPrevented&&onSearch){event.preventDefault();onSearch(value);}}} onFocus={event=>{setFocused(true);onFocus?.(event);}} onBlur={onBlur}/>{clearable&&value&&<button type="button" aria-label="Clear search" disabled={props.disabled} onClick={()=>{setValue('');input.current?.focus();}}><CircleX size={17}/></button>}</div>;
  return <div className={classes('prism-search-field',className)} style={style} data-focused={focused||undefined} onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget))setFocused(false);}}>
    {floating?<GlassSurface variant={variant} appearance={appearance} tintLevel={tintLevel} tint={tint} dimming={dimming} preset={preset??'search'} backdrop={backdrop} refractionTarget={refractionTarget} optics={optics} present={present} onPresenceChange={onPresenceChange} className="prism-search-surface">{body}</GlassSurface>:<div className="prism-search-inline">{body}</div>}
    {cancelable&&focused&&<button type="button" className="prism-search-cancel" onClick={()=>{setValue('');setFocused(false);input.current?.blur();onCancel?.();}}>{cancelLabel}</button>}
  </div>;
});

export interface GlassStepperProps extends Omit<HTMLAttributes<HTMLDivElement>,'defaultValue'|'onChange'> {value?:number;defaultValue?:number;onValueChange?:(value:number)=>void;min?:number;max?:number;step?:number;disabled?:boolean;label?:string}
export function GlassStepper({value:controlled,defaultValue=0,onValueChange,min=0,max=100,step=1,disabled=false,label='Value',className,onKeyDown,...props}:GlassStepperProps){
  if(!Number.isFinite(min)||!Number.isFinite(max)||!Number.isFinite(step)||max<min||step<=0)throw new RangeError('Invalid stepper range');
  const [raw,setValue]=useControllable(controlled,defaultValue,onValueChange),value=Math.max(min,Math.min(max,Number.isFinite(raw)?raw:min));
  const latest=useRef({value,disabled});latest.current={value,disabled};const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),repeater=useRef<ReturnType<typeof setInterval>|undefined>(undefined),pointer=useRef<number|null>(null);
  function stop(){if(timer.current)clearTimeout(timer.current);if(repeater.current)clearInterval(repeater.current);timer.current=undefined;repeater.current=undefined;pointer.current=null;}
  function change(direction:number){if(latest.current.disabled)return;const next=Math.max(min,Math.min(max,Math.round((latest.current.value+direction*step)*1e10)/1e10));if(next!==latest.current.value){latest.current.value=next;setValue(next);}}
  useEffect(()=>{const cancel=()=>stop();window.addEventListener('blur',cancel);return()=>{stop();window.removeEventListener('blur',cancel);};},[]);
  useEffect(()=>{if(disabled)stop();},[disabled]);
  return <div {...props} className={classes('prism-stepper',className)} role="group" aria-label={`${label}: ${value}`} data-disabled={disabled||undefined} onKeyDown={event=>{onKeyDown?.(event);if(event.defaultPrevented||disabled)return;if(['ArrowUp','ArrowRight','+','ArrowDown','ArrowLeft','-'].includes(event.key)){event.preventDefault();change(['ArrowUp','ArrowRight','+'].includes(event.key)?1:-1);}if(event.key==='Home'){event.preventDefault();setValue(min);}if(event.key==='End'){event.preventDefault();setValue(max);}}}>
    {([-1,1] as const).map(direction=><button key={direction} type="button" disabled={disabled||(direction<0?value<=min:value>=max)} aria-label={`${direction<0?'Decrease':'Increase'} ${label}`} onPointerDown={event=>{if(event.button!==0||pointer.current!==null)return;pointer.current=event.pointerId;event.currentTarget.setPointerCapture(event.pointerId);change(direction);timer.current=setTimeout(()=>{change(direction);repeater.current=setInterval(()=>change(direction),100);},450);}} onPointerUp={event=>{if(pointer.current===event.pointerId)stop();}} onPointerCancel={stop} onLostPointerCapture={stop} onClick={event=>{if(event.detail===0)change(direction);}}>{direction<0?<Minus size={19}/>:<Plus size={19}/>}</button>)}
    <output className="prism-visually-hidden" aria-live="polite">{value}</output>
  </div>;
}

export interface GlassPageControlProps extends Omit<HTMLAttributes<HTMLDivElement>,'onChange'>,Pick<MaterialProps,'appearance'|'variant'|'tint'|'dimming'> {count:number;value?:number;defaultValue?:number;onValueChange?:(value:number)=>void;background?:'automatic'|'prominent'|'minimal'}
export function GlassPageControl({count,value:controlled,defaultValue=0,onValueChange,background='automatic',appearance,variant,tint,dimming,className,style,...props}:GlassPageControlProps){
  if(!Number.isInteger(count)||count<1||count>1000)throw new RangeError('Page count must be in 1–1000');
  const [raw,setValue]=useControllable(controlled,defaultValue,onValueChange),value=Math.max(0,Math.min(count-1,Math.round(raw))),[active,setActive]=useState(false),pointer=useRef<number|null>(null),buttons=useRef<(HTMLButtonElement|null)[]>([]);
  const visible=Math.min(7,count),start=Math.max(0,Math.min(count-visible,value-Math.floor(visible/2)));
  function select(next:number){if(next!==value)setValue(next);}
  return <div {...props} className={classes('prism-page-control',className)} role="group" aria-label={props['aria-label']??'Pages'} style={{width:visible*17+24,...style}} onFocusCapture={()=>setActive(true)} onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget))setActive(false);}} onPointerDown={event=>{if(background==='minimal'||event.button!==0)return;pointer.current=event.pointerId;event.currentTarget.setPointerCapture(event.pointerId);setActive(true);}} onPointerMove={event=>{if(pointer.current!==event.pointerId)return;const rect=event.currentTarget.getBoundingClientRect();const ratio=(event.clientX-rect.left-20)/Math.max(1,rect.width-40);select(Math.max(0,Math.min(count-1,Math.round(ratio*(count-1)))));}} onPointerUp={()=>{pointer.current=null;setActive(false);}} onPointerCancel={()=>{pointer.current=null;setActive(false);}}>
    {background!=='minimal'&&<GlassSurface preset="page-control" appearance={appearance} variant={variant} tint={tint} dimming={dimming} present={background==='prominent'||active} className="prism-page-control-material" aria-hidden="true"/>}
    <div className="prism-page-dots">{Array.from({length:visible},(_,i)=>{const page=start+i,edge=count>visible&&((i===0&&start>0)||(i===visible-1&&start+visible<count));return <button key={page} ref={node=>{buttons.current[page]=node;}} type="button" aria-label={`Page ${page+1} of ${count}`} aria-current={page===value?'page':undefined} tabIndex={page===value?0:-1} data-edge={edge||undefined} onClick={()=>select(page)} onKeyDown={event=>{const rtl=getComputedStyle(event.currentTarget).direction==='rtl';const delta=(event.key==='ArrowRight'?1:-1)*(rtl?-1:1);if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?count-1:Math.max(0,Math.min(count-1,page+delta));select(next);requestAnimationFrame(()=>buttons.current[next]?.focus());}}}><span/></button>;})}</div>
  </div>;
}

export interface GlassPickerOption {value:string;label:string;disabled?:boolean}
export interface GlassWheelPickerProps extends Omit<HTMLAttributes<HTMLDivElement>,'defaultValue'|'onChange'> {options:readonly GlassPickerOption[];value?:string;defaultValue?:string;onValueChange?:(value:string)=>void;disabled?:boolean;label:string}
export function GlassWheelPicker({options,value:controlled,defaultValue,onValueChange,disabled=false,label,className,style,...props}:GlassWheelPickerProps){
  if(!options.length||new Set(options.map(option=>option.value)).size!==options.length)throw new Error('Wheel options must be nonempty and unique');
  const [value,setValue]=useControllable(controlled,defaultValue??options.find(option=>!option.disabled)?.value??options[0].value,onValueChange),index=Math.max(0,options.findIndex(option=>option.value===value)),id=useId(),drag=useRef<{id:number;y:number;index:number}|null>(null),wheel=useRef(0);
  function select(next:number,direction=1){next=Math.max(0,Math.min(options.length-1,next));while(options[next]?.disabled){next+=direction;if(next<0||next>=options.length)return;}if(!disabled&&options[next]&&options[next].value!==value)setValue(options[next].value);}
  return <div {...props} className={classes('prism-wheel-picker',className)} role="listbox" aria-label={label} aria-activedescendant={`${id}-${index}`} aria-disabled={disabled||undefined} tabIndex={disabled?-1:props.tabIndex??0} style={style} onKeyDown={event=>{if(disabled)return;const next=event.key==='ArrowDown'?index+1:event.key==='ArrowUp'?index-1:event.key==='Home'?0:event.key==='End'?options.length-1:event.key==='PageDown'?index+5:event.key==='PageUp'?index-5:null;if(next!==null){event.preventDefault();select(next,next<index?-1:1);}}} onWheel={event=>{if(disabled)return;wheel.current+=event.deltaY;if(Math.abs(wheel.current)>=18){select(index+Math.sign(wheel.current),Math.sign(wheel.current));wheel.current=0;}}} onPointerDown={event=>{if(disabled||event.button!==0)return;drag.current={id:event.pointerId,y:event.clientY,index};event.currentTarget.setPointerCapture(event.pointerId);event.currentTarget.focus();}} onPointerMove={event=>{const d=drag.current;if(!d||d.id!==event.pointerId)return;const next=d.index+Math.round((d.y-event.clientY)/34);select(next,next<index?-1:1);}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
    <div className="prism-wheel-selection" aria-hidden="true"/><div className="prism-wheel-options" style={{transform:`translateY(${102-index*34}px)`}}>{options.map((option,i)=><div key={option.value} id={`${id}-${i}`} role="option" aria-selected={value===option.value} aria-disabled={option.disabled||undefined} style={{opacity:Math.max(.12,1-Math.abs(i-index)*.23),transform:`rotateX(${Math.max(-70,Math.min(70,(index-i)*17))}deg)`}} onClick={()=>select(i,i<index?-1:1)}>{option.label}</div>)}</div>
  </div>;
}

export interface GlassColorWellProps extends Omit<InputHTMLAttributes<HTMLInputElement>,'type'|'size'|'value'|'defaultValue'> {value?:string;defaultValue?:string;onValueChange?:(value:string)=>void;label?:string}
export const GlassColorWell=forwardRef<HTMLInputElement,GlassColorWellProps>(function GlassColorWell({value:controlled,defaultValue='#0088ff',onValueChange,label='Color',className,style,onChange,...props},ref){
  const [value,setValue]=useControllable(controlled,defaultValue,onValueChange);
  return <span className={classes('prism-color-well',className)} style={{'--prism-well-color':value,...style} as CSSProperties}><input {...props} ref={ref} type="color" value={value} aria-label={props['aria-label']??label} onChange={event=>{onChange?.(event);if(!event.defaultPrevented)setValue(event.currentTarget.value);}}/><span aria-hidden="true"/></span>;
});

function parseDate(value:string){const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);if(!match)return null;const date=new Date(Date.UTC(+match[1],+match[2]-1,+match[3]));return date.toISOString().slice(0,10)===value?date:null;}
function localISO(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
export interface GlassDatePickerProps extends Omit<HTMLAttributes<HTMLDivElement>,'defaultValue'|'onChange'> {value?:string;defaultValue?:string;onValueChange?:(value:string)=>void;min?:string;max?:string;disabled?:boolean;label?:string;locale?:string;display?:'compact'|'inline'}
export function GlassDatePicker({value:controlled,defaultValue,onValueChange,min,max,disabled=false,label='Date',locale='en-US',display='compact',className,...props}:GlassDatePickerProps){
  const [value,setValue]=useControllable(controlled,defaultValue??localISO(new Date()),onValueChange),date=parseDate(value);if(!date)throw new TypeError('Dates must use YYYY-MM-DD');
  const [month,setMonth]=useState(()=>new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),1))),[focused,setFocused]=useState(value),grid=useRef<HTMLDivElement>(null);
  useEffect(()=>{setMonth(new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),1)));setFocused(value);},[value]);
  const year=month.getUTCFullYear(),m=month.getUTCMonth(),first=new Date(Date.UTC(year,m,1)).getUTCDay(),days=new Date(Date.UTC(year,m+1,0)).getUTCDate();
  useEffect(()=>{const current=parseDate(focused);if(current&&(current.getUTCFullYear()!==year||current.getUTCMonth()!==m))setFocused(new Date(Date.UTC(year,m,Math.min(current.getUTCDate(),days))).toISOString().slice(0,10));},[month]);
  const allowed=(iso:string)=>(!min||iso>=min)&&(!max||iso<=max)&&!disabled;
  const formatter=new Intl.DateTimeFormat(locale,{year:'numeric',month:'long',timeZone:'UTC'}),formatDay=new Intl.DateTimeFormat(locale,{dateStyle:'full',timeZone:'UTC'}),week=new Intl.DateTimeFormat(locale,{weekday:'short',timeZone:'UTC'});
  function select(iso:string){if(allowed(iso)){setFocused(iso);setValue(iso);}}
  function moveFocus(iso:string,delta:number){const next=parseDate(iso)!;next.setUTCDate(next.getUTCDate()+delta);const text=next.toISOString().slice(0,10);if(!allowed(text))return;setMonth(new Date(Date.UTC(next.getUTCFullYear(),next.getUTCMonth(),1)));setFocused(text);requestAnimationFrame(()=>grid.current?.querySelector<HTMLButtonElement>(`[data-date="${text}"]`)?.focus());}
  const calendar=<div className="prism-calendar"><div className="prism-calendar-heading"><strong>{formatter.format(month)}</strong><span><button type="button" disabled={disabled} aria-label="Previous month" onClick={()=>setMonth(new Date(Date.UTC(year,m-1,1)))}><ChevronLeft size={20}/></button><button type="button" disabled={disabled} aria-label="Next month" onClick={()=>setMonth(new Date(Date.UTC(year,m+1,1)))}><ChevronRight size={20}/></button></span></div><div className="prism-calendar-week" aria-hidden="true">{Array.from({length:7},(_,i)=><span key={i}>{week.format(new Date(Date.UTC(2026,0,4+i))).slice(0,3)}</span>)}</div><div className="prism-calendar-days" role="grid" aria-label={formatter.format(month)} ref={grid}>{Array.from({length:Math.ceil((first+days)/7)},(_,row)=><div role="row" key={row}>{Array.from({length:7},(_,column)=>{const day=row*7+column-first+1;if(day<1||day>days)return <span role="gridcell" key={column}/>;const iso=`${year}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;return <span role="gridcell" key={column} aria-selected={iso===value}><button type="button" data-date={iso} disabled={!allowed(iso)} aria-label={formatDay.format(parseDate(iso)!)} tabIndex={iso===focused?0:-1} onClick={()=>select(iso)} onKeyDown={event=>{const delta=event.key==='ArrowLeft'?-1:event.key==='ArrowRight'?1:event.key==='ArrowUp'?-7:event.key==='ArrowDown'?7:event.key==='Home'?-column:event.key==='End'?6-column:null;if(delta!==null){event.preventDefault();moveFocus(iso,delta);}if(event.key==='PageUp'||event.key==='PageDown'){event.preventDefault();const next=new Date(Date.UTC(year,m+(event.key==='PageUp'?-1:1),Math.min(day,28)));moveFocus(iso,Math.round((next.getTime()-parseDate(iso)!.getTime())/86400000));}}}>{day}</button></span>;})}</div>)}</div></div>;
  return <div {...props} className={classes('prism-date-picker',className)}>{display==='inline'?calendar:<GlassPopover trigger={new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeZone:'UTC'}).format(date)} triggerLabel={label} triggerProps={{disabled,emphasis:'bordered'}} aria-label={label} className="prism-calendar-popover">{disabled?<span>{label}</span>:calendar}</GlassPopover>}</div>;
}
