import {useEffect,useRef,useState,type CSSProperties,type ReactNode} from 'react';
import {createRoot} from 'react-dom/client';
import {Plus,MoreHorizontal,ChevronLeft,Undo2,Redo2,Share2,Grid2X2,Compass,Heart,Play,SkipForward,Music,Phone,MessageCircle,Mail,Copy,Trash2,Pin,Bold,Italic,Underline,Scissors,Clipboard,Wifi,Bluetooth,Sun,Moon,Clock,Cloud,Check,Search,Folder,FileText,Download,SquarePen,Volume2,CalendarDays} from 'lucide-react';
import {GlassProvider,GlassMediaScene,GlassSurface,GlassButton,GlassSwitch,GlassSlider,GlassTabs,GlassToolbar,GlassPopover,GlassChip,GlassToken,GlassDock,GlassDockItem,GlassControlTile,GlassNotification,GlassLiveActivity,GlassWidget,GlassSnippet,GlassDisclosure,GlassScrollArea,GlassBackgroundExtension,GlassSidebar,GlassNavigationBar,GlassTabBar,GlassInputAccessory,GlassListRow,MaterialSurface,GlassProgress,GlassBadge,GlassTextField,GlassSearchField,GlassStepper,GlassPageControl,GlassWheelPicker,GlassColorWell,GlassDatePicker,GlassMenu,GlassContextMenu,GlassSelect,GlassEditMenu,GlassActionSheet,GlassAlertDialog,GlassSheet,GlassShareSheet,type GlassMenuItem,type GlassSheetDetent,type MaterialProps} from '../src/react.js';
import {allEntries} from './catalog-data.js';
const query=new URLSearchParams(location.search),id=query.get('component')??'dock',entry=allEntries.find(item=>item.id===id)??allEntries[0],family=entry.family;
const appearance=query.get('appearance')==='dark'?'dark':'light',background=query.get('background')??'photo',state=query.get('state')??'default',mode=query.get('material')??'system';
const at=(x:number,y:number,width?:number,height?:number):CSSProperties=>({position:'absolute',left:x,top:y-62,transform:'translate(-50%,-50%)',...(width?{width}:{}),...(height?{height}:{})});
const material:MaterialProps=mode==='system'?{appearance}:{appearance,variant:'clear',dimming:mode==='dimmed'?.35:0,tint:[1,1,1,.035]};
const initiallyOpen=['alert','action-sheet','sheet','popover','share','menus','edit-menu','quick-actions'].includes(family)&&state!=='closed';
function Scene(){
 const source=useRef<HTMLCanvasElement>(null),primary=useRef<HTMLButtonElement>(null),[ready,setReady]=useState(false),[version,setVersion]=useState(0),[count,setCount]=useState(3),[choice,setChoice]=useState('second'),[enabled,setEnabled]=useState(true),[value,setValue]=useState(50),[text,setText]=useState('Prism'),[search,setSearch]=useState(''),[date,setDate]=useState('2026-09-25'),[color,setColor]=useState('#0088ff'),[page,setPage]=useState(2),[open,setOpen]=useState(initiallyOpen),[selected,setSelected]=useState(state==='selected'),[tab,setTab]=useState(state==='selected'?'explore':'library'),[notice,setNotice]=useState(''),[dismissed,setDismissed]=useState(false),[detent,setDetent]=useState<GlassSheetDetent>(state==='expanded'?'large':'medium');
 const disabled=state==='disabled';
 useEffect(()=>{const canvas=source.current!,ctx=canvas.getContext('2d')!;let dead=false;
   function finish(){if(dead)return;setVersion(v=>v+1);setReady(true);}
   if(background==='photo'){const image=new Image();image.onload=()=>{if(dead)return;ctx.drawImage(image,0,0,402,812);finish();};image.onerror=()=>{ctx.fillStyle='#98a386';ctx.fillRect(0,0,402,812);finish();};image.src='./assets/catalog/background-photo.png';}
   else {ctx.fillStyle=background==='dark'?'rgb(20 26 36)':'rgb(240 242 247)';ctx.fillRect(0,0,402,812);if(background==='grid'){for(let x=0;x<402;x+=20){ctx.fillStyle='#0088ff';ctx.fillRect(x,0,3,812);}for(let y=-2;y<812;y+=20){ctx.fillStyle='#ff3b30';ctx.fillRect(0,y,402,3);}}finish();}
   return()=>{dead=true;};
 },[]);
 useEffect(()=>{if(!ready||state!=='pressed')return;const frame=requestAnimationFrame(()=>{const node=primary.current??document.querySelector<HTMLButtonElement>('.prism-dock-item,.prism-control-tile,.prism-chip');if(!node)return;const rect=node.getBoundingClientRect();node.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:777,button:0,clientX:rect.left+rect.width*.28,clientY:rect.top+rect.height*.5}));});return()=>cancelAnimationFrame(frame);},[ready]);
 const menuItems:GlassMenuItem[]=[{id:'copy',label:'Copy',icon:<Copy/>,onSelect:()=>setNotice('Copied')},{id:'share',label:'Share',icon:<Share2/>,onSelect:()=>setNotice('Share selected')},{id:'favorite',label:'Favorite',checked:enabled,separatorBefore:true,keepOpen:true,onSelect:()=>setEnabled(v=>!v)},{id:'unavailable',label:'Unavailable',icon:<Pin/>,disabled:true},{id:'delete',label:'Delete',icon:<Trash2/>,destructive:true,onSelect:()=>setNotice('Delete selected')}];
 const pageTitle=family==='chips'?'buttons':family==='quick-actions'?'menus':family;
 const button=(label:string,x:number,y:number,extra:Record<string,unknown>={})=><GlassButton {...material} {...extra} style={at(x,y)} onClick={(extra.onClick as (()=>void)|undefined)??(()=>setNotice(`${label} selected`))}>{label}</GlassButton>;
 const controls=<><GlassTabs {...material} aria-label="View" value={choice} onValueChange={setChoice} items={[{value:'first',label:'First'},{value:'second',label:'Second'},{value:'third',label:'Third'}]} style={at(201,180,342)}/><GlassStepper label="Amount" value={count} onValueChange={setCount} min={0} max={10} disabled={disabled} style={at(106,270)}/><div style={at(296,270)}><GlassSelect {...material} label="Quality" disabled={disabled} value={choice} onValueChange={setChoice} options={[{value:'first',label:'Low'},{value:'second',label:'Medium'},{value:'third',label:'High'}]}/></div><GlassTextField {...material} aria-label="Name" value={text} onValueChange={setText} disabled={disabled} style={at(201,360,342)}/><div style={at(168,450)}><GlassDatePicker value={date} onValueChange={setDate} label="Date" disabled={disabled}/></div><GlassColorWell label="Color" value={color} onValueChange={setColor} disabled={disabled} style={at(281,450)}/><GlassProgress value={.65} label="Download" style={at(201,530,300)}/><div className="scene-loading" style={at(201,585)}><GlassProgress kind="circular"/><span>Loading</span></div><GlassPageControl {...material} count={7} value={page} onValueChange={setPage} background="prominent" style={at(201,650)}/><div className="scene-input-pair" style={at(201,740)}><GlassSwitch aria-label="Wi-Fi" checked={enabled} onCheckedChange={setEnabled} disabled={disabled}/><GlassSlider aria-label="Volume" value={value} onValueChange={setValue} disabled={disabled} style={{width:190}}/></div></>;
 let content:ReactNode;
 if(family==='buttons'||family==='chips')content=<>{button('Continue',106,180,{'data-preview-press':'',ref:primary,disabled,loading:state==='loading'})}{button('Continue',296,180,{emphasis:'prominent',disabled})}{button('Continue',106,260,{disabled:true})}{button('Continue',296,260,{emphasis:'prominent',disabled:true})}{button('Small',106,340,{size:'small'})}{button('Large',296,340,{size:'large'})}<GlassButton {...material} shape="circle" aria-label="Add" style={at(106,420)} onClick={()=>setNotice('Added')}><Plus size={17}/></GlassButton><GlassButton {...material} shape="circle" emphasis="prominent" aria-label="Add prominently" style={at(296,420)} onClick={()=>setNotice('Added')}><Plus size={17}/></GlassButton>{button('Delete',106,500,{intent:'destructive'})}{button('Delete',296,500,{intent:'destructive',emphasis:'prominent'})}{button('Saving',106,580,{loading:true})}{button('Plain',296,580,{emphasis:'plain'})}<small className="scene-caption" style={at(201,650)}>Custom regular · interactive</small><div className="scene-chip-row" style={at(201,710)}><GlassChip {...material} selected={selected} onSelectedChange={setSelected} disabled={disabled}>Filter</GlassChip><GlassChip {...material} selected onSelectedChange={()=>setNotice('Selected chip')}>Selected</GlassChip></div></>;
 else if(family==='inputs')content=controls;
 else if(family==='wheel')content=<><GlassWheelPicker label="Number" value={String(count)} onValueChange={v=>setCount(+v)} disabled={disabled} options={Array.from({length:10},(_,i)=>({value:String(i),label:String(i)}))} style={at(201,300,160,216)}/><div className="scene-calendar" style={at(201,610,342,330)}><GlassDatePicker value={date} onValueChange={setDate} display="inline" disabled={disabled}/></div></>;
 else if(family==='standard-materials')content=<div className="scene-standard-stack" style={at(201,440)}>{(['ultra-thin','thin','regular','thick'] as const).map((kind,i)=><MaterialSurface key={kind} material={kind} appearance={appearance}><div className="scene-standard-labels"><strong>{['Ultra thin','Thin','Regular','Thick'][i]}</strong><span>Primary label</span><span className="prism-secondary">Secondary label</span></div></MaterialSurface>)}</div>;
 else if(family==='alert')content=<>{button('Present',201,210,{ref:primary,onClick:()=>setOpen(true)})}<GlassAlertDialog returnFocusRef={primary} {...material} source={source} sourceVersion={version} open={open&&ready} onOpenChange={setOpen} title="Delete item?" message="This item will be removed from your collection." actions={[{label:'Cancel',intent:'cancel'},{label:'Delete',intent:'destructive',onSelect:()=>setNotice('Item removed')}]}/></>;
 else if(family==='action-sheet')content=<div style={at(201,210)}><GlassActionSheet {...material} source={source} sourceVersion={version} align="center" trigger="Present" open={open} onOpenChange={setOpen} title="Choose an action" actions={[{id:'save',label:'Save to collection',onSelect:()=>setNotice('Saved')},{id:'share',label:'Share item',onSelect:()=>setNotice('Share selected')},{id:'delete',label:'Delete item',destructive:true,onSelect:()=>setNotice('Item removed')}]}/></div>;
 else if(family==='popover')content=<div style={at(201,210)}><GlassPopover {...material} source={source} sourceVersion={version} align="center" trigger="Present" open={open} onOpenChange={setOpen} aria-label="Options" className="scene-native-popover"><h3>Options</h3><p>A focused surface for a short task.</p><GlassButton emphasis="prominent" onClick={()=>setOpen(false)}>Save changes</GlassButton></GlassPopover></div>;
 else if(family==='sheet')content=<>{button('Present',201,210,{ref:primary,onClick:()=>setOpen(true)})}<GlassSheet returnFocusRef={primary} {...material} source={source} sourceVersion={version} title="Collection" open={open&&ready} onOpenChange={setOpen} detent={detent} onDetentChange={setDetent} leading={<GlassButton emphasis="bordered" onClick={()=>setOpen(false)}>Cancel</GlassButton>} trailing={<GlassButton emphasis="bordered" onClick={()=>setOpen(false)} style={{fontWeight:600}}>Done</GlassButton>}><h3>Details</h3><p>A native sheet keeps the content readable.</p><GlassTextField appearance={appearance} value={text} onValueChange={setText} aria-label="Name"/></GlassSheet></>;
 else if(family==='share')content=<>{button('Share',201,210,{ref:primary,onClick:()=>setOpen(true)})}<GlassShareSheet returnFocusRef={primary} {...material} source={source} sourceVersion={version} open={open&&ready} onOpenChange={setOpen} title="Field notes" subtitle="A shared collection" detent={detent} onDetentChange={setDetent} destinations={[{id:'message',label:'Messages',icon:<MessageCircle/>,onSelect:()=>setNotice('Messages selected')},{id:'mail',label:'Mail',icon:<Mail/>,onSelect:()=>setNotice('Mail selected')},{id:'copy',label:'Copy',icon:<Copy/>,onSelect:()=>setNotice('Copied')}]} actions={[{id:'copy-link',label:'Copy link',icon:<Copy/>,onSelect:()=>setNotice('Link copied')},{id:'save',label:'Save to collection',icon:<Folder/>,onSelect:()=>setNotice('Saved to collection')}]}/></>;
 else if(family==='menus'||family==='quick-actions')content=<><div style={at(201,220)}><GlassMenu {...material} source={source} sourceVersion={version} align="center" trigger={<><MoreHorizontal size={18}/> Actions</>} items={menuItems} open={open} onOpenChange={setOpen} aria-label="Actions"/></div><GlassContextMenu items={menuItems} label="Context actions" style={at(201,560)}><GlassSurface {...material} preset="popover" style={{padding:28}}>Context menu</GlassSurface></GlassContextMenu></>;
 else if(family==='edit-menu')content=<><div style={at(201,240)}><GlassEditMenu {...material} source={source} sourceVersion={version} align="center" trigger="Edit selection" open={open} onOpenChange={setOpen} items={[{id:'cut',label:'Cut',onSelect:()=>setText('')},{id:'copy',label:'Copy',onSelect:()=>setNotice('Copied')},{id:'paste',label:'Paste',onSelect:()=>setText('Copied text')},{id:'all',label:'Select All',onSelect:()=>setNotice('All text selected')}]}/></div><GlassTextField {...material} value={text} onValueChange={setText} aria-label="Editable selection" style={at(201,340,342)}/></>;
 else if(family==='navigation'||family==='scroll')content=<><GlassScrollArea className="scene-native-scroll" edgeEffect="soft"><div className="scene-native-list">{Array.from({length:14},(_,i)=><MaterialSurface key={i} appearance={appearance} material="regular">Collection item {i+1}</MaterialSurface>)}</div></GlassScrollArea><GlassNavigationBar {...material} title="Collection" largeTitle leading={<GlassButton shape="circle" aria-label="Back" onClick={()=>setNotice('Back')}><ChevronLeft size={22}/></GlassButton>} trailing={<><GlassButton aria-label="Add" onClick={()=>setNotice('Added')}><Plus size={20}/></GlassButton><GlassButton aria-label="More" onClick={()=>setNotice('More actions')}><MoreHorizontal size={20}/></GlassButton></>} className="scene-navigation"/><GlassToolbar {...material} preset="toolbar" className="scene-bottom-tools" aria-label="Editing tools"><GlassButton aria-label="Undo" onClick={()=>setNotice('Undone')}><Undo2 size={20}/></GlassButton><GlassButton aria-label="Redo" onClick={()=>setNotice('Redone')}><Redo2 size={20}/></GlassButton><GlassButton aria-label="Share" onClick={()=>setNotice('Share selected')}><Share2 size={20}/></GlassButton></GlassToolbar></>;
 else if(family==='tabs')content=<><h2 className="scene-tab-title">{tab==='library'?'Library':tab==='explore'?'Explore':tab==='saved'?'Saved':'Search'}</h2>{tab==='search'&&<GlassSearchField {...material} value={search} onValueChange={setSearch} onSearch={()=>setNotice(`Searching: ${search}`)} style={at(201,190,350)}/>}<div className="scene-tab-bar"><GlassTabBar {...material} value={tab} onValueChange={setTab} minimized={state==='minimized'} items={[{value:'library',label:'Library',icon:<Grid2X2/>,badge:2},{value:'explore',label:'Explore',icon:<Compass/>},{value:'saved',label:'Saved',icon:<Heart/>},{value:'search',label:'Search',icon:<Search/>}]} accessory={<><Music size={19}/><span style={{flex:1}}>Now playing</span><button type="button" aria-label="Play" onClick={()=>setNotice('Playing')}><Play size={18}/></button><button type="button" aria-label="Next" onClick={()=>setNotice('Next track')}><SkipForward size={18}/></button></>}/></div></>;
 else if(family==='search')content=<><GlassNavigationBar {...material} title="Search" largeTitle/><GlassSearchField {...material} value={search} onValueChange={setSearch} disabled={disabled} onSearch={()=>setNotice(`Searching: ${search}`)} style={at(201,200,354)}/><div className="scene-search-results" style={at(201,390,350)}>{['Field notes','Garden collection','Saved ideas'].filter(item=>item.toLowerCase().includes(search.toLowerCase())).map(item=><MaterialSurface appearance={appearance} material="thin" key={item}><GlassListRow chevron>{item}</GlassListRow></MaterialSurface>)}</div></>;
 else if(family==='sidebar')content=<GlassSidebar {...material} heading="Your workspace" value={tab} onValueChange={setTab} items={[{value:'library',label:'Overview',icon:<Grid2X2/>},{value:'recent',label:'Recent files',icon:<Clock/>},{value:'collections',label:'Collections',icon:<Folder/>},{value:'shared',label:'Shared with you',icon:<Share2/>}]} style={at(142,420,240,470)}/>;
 else if(family==='dock')content=<GlassDock {...material} dimming={mode==='dimmed'?.35:0} tint={[1,1,1,.035]} style={at(201,430)} aria-label="App dock"><GlassDockItem label="Phone" onClick={()=>setNotice('Phone selected')}><Phone fill="currentColor"/></GlassDockItem><GlassDockItem label="Browser" onClick={()=>setNotice('Browser selected')}><Compass/></GlassDockItem><GlassDockItem label="Messages" onClick={()=>setNotice('Messages selected')}><MessageCircle fill="currentColor"/></GlassDockItem><GlassDockItem label="Music" onClick={()=>setNotice('Music selected')}><Music fill="currentColor"/></GlassDockItem></GlassDock>;
 else if(family==='controls')content=<div className="scene-controls-grid" style={at(201,420,290)}><GlassControlTile {...material} label="Wi-Fi" symbol={<Wifi/>} selected={selected} onSelectedChange={setSelected} disabled={disabled}/><GlassControlTile {...material} label="Bluetooth" symbol={<Bluetooth/>} defaultSelected disabled={disabled}/><GlassControlTile {...material} label="Focus" subtitle="Personal" symbol={<Moon/>} size="wide" disabled={disabled}/><GlassControlTile {...material} label="Brightness" symbol={<Sun/>} size="large" disabled={disabled}/><GlassControlTile {...material} label="Volume" symbol={<Volume2/>} size="large" disabled={disabled}/></div>;
 else if(family==='notification')content=!dismissed?<GlassNotification {...material} title="Download complete" appName="PRISM" message="Your collection is ready to view." icon={<Download/>} time="now" expanded={state==='expanded'} onActivate={()=>setNotice('Collection opened')} onDismiss={()=>setDismissed(true)} actions={[{id:'open',label:'View collection',onSelect:()=>setNotice('Collection opened')},{id:'later',label:'Remind me later',onSelect:()=>setDismissed(true)}]} style={at(201,300,370)}/>:button('Show notification',201,300,{onClick:()=>setDismissed(false)});
 else if(family==='live-activity')content=<GlassLiveActivity {...material} presentation={state==='expanded'?'expanded':state==='minimized'?'compact':'banner'} leading={<Clock size={24}/>} trailing={<GlassProgress kind="circular" value={.7}/>} style={at(201,400)}><strong>On the way</strong><p style={{fontSize:13,margin:'5px 0 0',opacity:.6}}>About 4 minutes remaining</p></GlassLiveActivity>;
 else if(family==='widgets')content=<><GlassWidget {...material} renderingMode={state==='selected'?'tinted':'clear'} style={at(120,280)}><Cloud size={24}/><strong className="scene-weather-value">22°</strong><span>Home</span><small>Partly cloudy</small></GlassWidget><GlassWidget {...material} size="medium" renderingMode="clear" style={at(201,540)}><small>FRIDAY</small><strong className="scene-weather-value">25</strong><span>September</span><GlassButton size="small" emphasis="bordered" onClick={()=>setNotice('Calendar opened')}>Open calendar</GlassButton></GlassWidget></>;
 else if(family==='snippet')content=<GlassSnippet {...material} style={at(201,390)}><h3>Ready to continue?</h3><p>Your collection has 12 items.</p><GlassButton emphasis="prominent" onClick={()=>setNotice('Collection opened')}>Open collection</GlassButton></GlassSnippet>;
 else if(family==='disclosure')content=<MaterialSurface appearance={appearance} style={at(201,360,342)}><GlassDisclosure title="Collection details" defaultOpen={state==='expanded'}><p>12 items, updated today.</p><GlassButton onClick={()=>setNotice('Details opened')}>View details</GlassButton></GlassDisclosure><GlassDisclosure title="Sharing"><p>Only you can view this collection.</p></GlassDisclosure></MaterialSurface>;
 else if(family==='keyboard')content=<><GlassTextField appearance={appearance} label="A native input opens the real device keyboard" value={text} onValueChange={setText} clearable style={at(201,300,342)}/><GlassInputAccessory {...material} aria-label="Text formatting" style={at(201,630,342)}><GlassButton aria-label="Bold" onClick={()=>setNotice('Bold enabled')}><Bold size={18}/></GlassButton><GlassButton aria-label="Italic" onClick={()=>setNotice('Italic enabled')}><Italic size={18}/></GlassButton><GlassButton aria-label="Underline" onClick={()=>setNotice('Underline enabled')}><Underline size={18}/></GlassButton><GlassButton onClick={()=>setNotice('Editing done')}>Done</GlassButton></GlassInputAccessory></>;
 else if(family==='content')content=<GlassScrollArea className="scene-content-area"><MaterialSurface appearance={appearance} material="regular"><h3>{entry.title}</h3><p>Content stays clear and readable beneath the floating controls.</p><GlassListRow detail="12" chevron>Collection</GlassListRow><GlassListRow detail="Today" chevron>Updated</GlassListRow><GlassDisclosure title="More details"><p>Use the standard material appropriate to this content.</p></GlassDisclosure></MaterialSurface><MaterialSurface appearance={appearance} material="thin"><h3>Supporting content</h3><p>This area uses a standard material, without optical refraction.</p><GlassProgress value={.65} label="Progress"/></MaterialSurface></GlassScrollArea>;
 else content=<div className="scene-scope-note" style={at(201,380,320)}><strong>{entry.title}</strong><p>{entry.note}</p><a href={entry.url} target="_blank" rel="noreferrer">Read Apple’s guideline</a></div>;
 return <GlassProvider appearance={appearance}><div className="catalog-scene-root" data-appearance={appearance} data-scene-ready={ready}><GlassMediaScene source={source} sourceVersion={version} appearance={appearance} variant="regular" className="catalog-scene"><canvas ref={source} width={402} height={812} className="scene-backdrop"/><div className="prism-media-controls">{!['navigation','tabs','search'].includes(family)&&<div className="scene-reference-heading"><strong>Prism Glass</strong><span>{pageTitle}</span></div>}{content}{notice&&<div className="scene-status" role="status">{notice}</div>}</div></GlassMediaScene></div></GlassProvider>;
}
createRoot(document.getElementById('root')!).render(<Scene/>);
