import {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,ArrowUpRight,ChevronLeft,Columns2,Monitor,Sun,Moon} from 'lucide-react';
import {allEntries,catalogEntries,categoryLabels,nativeFamilies,type CatalogState} from './catalog-data.js';
import nativeFiles from '../docs/visual/catalog/manifest.json';
function ScaledFrame({children}:{children:React.ReactNode}){
 const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const node=root.current!,observer=new ResizeObserver(entries=>node.style.setProperty('--preview-scale',String(entries[0].contentRect.width/402)));observer.observe(node);return()=>observer.disconnect();},[]);
 return <div className="reference-frame" ref={root}><div>{children}</div></div>;
}
function Catalog(){
 const initial=new URLSearchParams(location.search).get('component')??'dock';
 const [selected,setSelected]=useState(allEntries.some(item=>item.id===initial)?initial:'dock'),[query,setQuery]=useState(''),[appearance,setAppearance]=useState('light'),[background,setBackground]=useState('photo'),[state,setState]=useState<CatalogState>('default'),[material,setMaterial]=useState('system'),[comparison,setComparison]=useState(true),[imageMissing,setImageMissing]=useState(false);
 const entry=allEntries.find(item=>item.id===selected)!;
 const family=entry.family==='chips'?'buttons':entry.family==='quick-actions'?'menus':entry.family;
 const source=`./assets/catalog/${family}-${background}-${appearance}.png`;
 const hasNative=nativeFamilies.has(family)&&nativeFiles.includes(`${family}-${background}-${appearance}.png`);
 const scene=`./catalog-scene.html?${new URLSearchParams({component:selected,appearance,background,state,material})}`;
 useEffect(()=>{setImageMissing(false);},[source]);
 function choose(id:string){const next=allEntries.find(item=>item.id===id)!;setSelected(id);setState(next.states[0]);history.replaceState(null,'',`?component=${id}`);}
 const groups=Object.entries(categoryLabels).map(([key,label])=>({key,label,items:allEntries.filter(item=>item.category===key&&(item.title+' '+item.api).toLowerCase().includes(query.toLowerCase()))})).filter(group=>group.items.length);
 return <div className="catalog-app"><header className="catalog-header"><a className="catalog-brand" href="./"><ChevronLeft size={17}/> Prism Glass</a><span>iOS 27 component catalog</span><a href="https://developer.apple.com/design/human-interface-guidelines/components" target="_blank" rel="noreferrer">Apple HIG <ArrowUpRight size={14}/></a></header>
 <aside className="catalog-sidebar"><h1>Every role,<br/>in context.</h1><p>All {catalogEntries.length} HIG component entries, with their iOS material rules.</p><label className="catalog-search"><Search size={16}/><input type="search" placeholder="Find a component" aria-label="Find a component" value={query} onChange={e=>setQuery(e.target.value)}/></label><nav aria-label="Component catalog">{groups.map(group=><section key={group.key}><h2>{group.label}</h2>{group.items.map(item=><button type="button" key={item.id} aria-current={item.id===selected?'page':undefined} onClick={()=>choose(item.id)}><span>{item.title}</span><i data-scope={item.scope} aria-label={item.scope}/></button>)}</section>)}</nav></aside>
 <main className="catalog-main"><div className="catalog-title"><div><p>{categoryLabels[entry.category]}</p><h2>{entry.title}</h2><code>{entry.api}</code></div><a href={entry.url} target="_blank" rel="noreferrer">Source guideline <ArrowUpRight size={15}/></a></div><p className="catalog-note">{entry.note}</p>
 <div className="catalog-controls"><label>Appearance<select aria-label="Catalog appearance" value={appearance} onChange={e=>setAppearance(e.target.value)}><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Background<select aria-label="Catalog background" value={background} onChange={e=>setBackground(e.target.value)}><option value="photo">Photo</option><option value="light">Light</option><option value="dark">Dark</option><option value="grid">Optical grid</option></select></label><label>State<select aria-label="Catalog state" value={state} onChange={e=>setState(e.target.value as CatalogState)}>{entry.states.map(value=><option key={value} value={value}>{value[0].toUpperCase()+value.slice(1)}</option>)}</select></label><label>Material<select aria-label="Catalog material" value={material} onChange={e=>setMaterial(e.target.value)}><option value="system">Component default</option><option value="clear">Clear · 0% dimming</option><option value="dimmed">Clear · 35% dimming</option></select></label><button type="button" aria-pressed={comparison} onClick={()=>setComparison(!comparison)}><Columns2 size={16}/> Reference</button></div>
 <div className="catalog-previews" data-comparison={comparison}>{comparison&&<section><header><span>Native base reference</span><small>{appearance} · {background}</small></header>{hasNative&&!imageMissing?<ScaledFrame><img src={source} alt={`Native iOS 27 ${family} base reference`} onError={()=>setImageMissing(true)}/></ScaledFrame>:<div className="reference-explanation"><strong>{entry.scope==='other-platform'?'Outside iOS':entry.scope==='system-owned'?'Owned by the system':'Material reference'}</strong><p>{entry.scope==='other-platform'?entry.note:entry.scope==='system-owned'?'The real OS supplies this interface. This catalog keeps that boundary explicit.':nativeFamilies.has(family)?'No native capture is available for this background. Choose Photo to compare the native base state.':'This composition uses the calibrated native material family. Its source and verification details are listed in the coverage record.'}</p><a href={entry.url} target="_blank" rel="noreferrer">Open the source <ArrowUpRight size={14}/></a></div>}</section>}
 <section><header><span>Live implementation</span><small>402 × 812 CSS pixels</small></header><ScaledFrame><iframe key={scene} src={scene} title={`${entry.title} live preview`} allow="clipboard-write"/></ScaledFrame></section></div>
 <footer className="catalog-footnote"><span>{entry.scope==='component'||entry.scope==='composition'?'Interact with the live preview. Its controls, menus and presentations work.':'Content, system-owned and other-platform entries are explicitly distinguished from Liquid Glass controls.'}</span><a href="https://github.com/Meapri/prism-glass/blob/main/docs/HIG_COVERAGE.md" target="_blank" rel="noreferrer">Coverage & measured differences <ArrowUpRight size={14}/></a></footer></main></div>;
}
createRoot(document.getElementById('root')!).render(<Catalog/>);
