import inventory from '../docs/HIG_INVENTORY.json';
export type CatalogState='default'|'pressed'|'disabled'|'selected'|'loading'|'open'|'closed'|'expanded'|'minimized';
export interface CatalogEntry {id:string;title:string;category:string;scope:string;url:string;family:string;states:readonly CatalogState[];api:string;note:string}
const families:Record<string,string>={
 'activity-views':'share','buttons':'buttons','context-menus':'menus','edit-menus':'edit-menu','home-screen-quick-actions':'quick-actions','menus':'menus','pop-up-buttons':'inputs','pull-down-buttons':'menus','toolbars':'navigation',
 'search-fields':'search','sidebars':'sidebar','tab-bars':'tabs','action-sheets':'action-sheet','alerts':'alert','page-controls':'inputs','popovers':'popover','scroll-views':'scroll','sheets':'sheet',
 'color-wells':'inputs','pickers':'wheel','segmented-controls':'inputs','sliders':'inputs','steppers':'inputs','text-fields':'inputs','toggles':'inputs','controls':'controls','live-activities':'live-activity','notifications':'notification','snippets':'snippet','widgets':'widgets',
 'disclosure-controls':'disclosure','progress-indicators':'inputs','boxes':'standard-materials','collections':'content','labels':'standard-materials','lists-and-tables':'content','split-views':'sidebar','charts':'content','image-views':'content','text-views':'content','web-views':'content','activity-rings':'content','gauges':'content',
 'virtual-keyboards':'keyboard','app-shortcuts':'system','status-bars':'system',
};
const apis:Record<string,string>={'activity-views':'GlassShareSheet','buttons':'GlassButton','context-menus':'GlassContextMenu','edit-menus':'GlassEditMenu','home-screen-quick-actions':'GlassContextMenu','menus':'GlassMenu','pop-up-buttons':'GlassSelect','pull-down-buttons':'GlassPullDownButton','toolbars':'GlassToolbar / GlassNavigationBar','search-fields':'GlassSearchField','sidebars':'GlassSidebar','tab-bars':'GlassTabBar','action-sheets':'GlassActionSheet','alerts':'GlassAlertDialog','page-controls':'GlassPageControl','popovers':'GlassPopover','scroll-views':'GlassScrollArea','sheets':'GlassSheet','color-wells':'GlassColorWell','pickers':'GlassWheelPicker / GlassDatePicker','segmented-controls':'GlassTabs','sliders':'GlassSlider','steppers':'GlassStepper','text-fields':'GlassTextField','toggles':'GlassSwitch','controls':'GlassControlTile','live-activities':'GlassLiveActivity','notifications':'GlassNotification','snippets':'GlassSnippet','widgets':'GlassWidget','disclosure-controls':'GlassDisclosure','progress-indicators':'GlassProgress','virtual-keyboards':'GlassTextField / GlassInputAccessory'};
const specialStates:Record<string,readonly CatalogState[]>={buttons:['default','pressed','disabled','loading'],controls:['default','pressed','selected','disabled'],notifications:['default','expanded'],widgets:['default','selected'],alerts:['open','closed'],sheets:['open','expanded','closed'],popovers:['open','closed'],'activity-views':['open','expanded','closed'],'action-sheets':['open','closed'],menus:['open','closed'],'context-menus':['open','closed'],'pull-down-buttons':['open','closed'],'home-screen-quick-actions':['open','closed'],'edit-menus':['open','closed'],'live-activities':['default','expanded','minimized'],'tab-bars':['default','selected','minimized'],'disclosure-controls':['default','expanded'],'search-fields':['default','disabled'],'text-fields':['default','disabled'],toggles:['default','disabled'],sliders:['default','disabled'],steppers:['default','disabled'],pickers:['default','disabled'],'color-wells':['default','disabled'],'pop-up-buttons':['default','disabled']};
export const catalogEntries:readonly CatalogEntry[]=inventory.items.map(item=>({
 id:item.id,title:item.title,category:item.category,scope:item.scope,url:item.url,family:families[item.id]??'not-ios',states:specialStates[item.id]??['default'],api:apis[item.id]??(item.scope==='standard-content'?'MaterialSurface + semantic content':item.scope==='system-owned'?'Native platform integration':'Not an iOS component'),
 note:item.scope==='other-platform'?'Apple does not define this component for iOS. Its source remains in the coverage inventory.':item.scope==='standard-content'?'Content stays in the content plane. Standard materials and semantic HTML provide its structure.':item.scope==='system-owned'?'The OS owns this experience. The web implementation uses the native platform handoff instead of drawing fake system chrome.':'Use the component’s native role and keep its content as ordinary interactive HTML.',
}));
export const customEntries:readonly CatalogEntry[]=[
 {id:'dock',title:'Clear dock',category:'custom-compositions',scope:'composition',url:'https://developer.apple.com/design/human-interface-guidelines/materials',family:'dock',states:['default','pressed'],api:'GlassDock / GlassDockItem',note:'Transparency follows the supplied iOS 27 dock reference. Generic demo symbols are separate from the material.'},
 {id:'chips',title:'Chips and tokens',category:'custom-compositions',scope:'composition',url:'https://developer.apple.com/documentation/swiftui/applying-liquid-glass-to-custom-views',family:'chips',states:['default','selected','disabled','pressed'],api:'GlassChip / GlassToken',note:'A custom capsule composition using native regular and tinted glass. Apple does not define a separate iOS chip control.'},
 {id:'standard-materials',title:'Standard materials',category:'foundations',scope:'standard-content',url:'https://developer.apple.com/design/human-interface-guidelines/materials',family:'standard-materials',states:['default'],api:'MaterialSurface',note:'Ultra-thin, thin, regular and thick materials belong in the content layer.'},
 {id:'background-extension',title:'Background extension',category:'foundations',scope:'composition',url:'https://developer.apple.com/design/human-interface-guidelines/sidebars',family:'sidebar',states:['default'],api:'GlassBackgroundExtension',note:'Extend a known image beneath floating navigation without duplicating interactive content.'},
];
export const allEntries=[...catalogEntries,...customEntries];
export const categoryLabels:Record<string,string>={'content':'Content','layout-and-organization':'Layout & organization','menus-and-actions':'Menus & actions','navigation-and-search':'Navigation & search','presentation':'Presentation','selection-and-input':'Selection & input','status':'Status','system-experiences':'System experiences','custom-compositions':'Custom compositions','foundations':'Materials & foundations'};
export const nativeFamilies=new Set(['buttons','inputs','wheel','navigation','tabs','alert','action-sheet','sheet','popover','menus','standard-materials']);
